# 关闭强制使用https，否则无法实现统一认证（或使用https）
cas.tgc.secure=false

cas.authn.mfa.globalProviderId=mfa-gauth
cas.authn.mfa.globalFailureMode=CLOSED

cas.authn.mfa.gauth.issuer=
cas.authn.mfa.gauth.label=
cas.authn.mfa.gauth.windowSize=3
cas.authn.mfa.gauth.codeDigits=6
cas.authn.mfa.gauth.timeStepSize=30
cas.authn.mfa.gauth.rank=0
cas.authn.mfa.gauth.trustedDeviceEnabled=false
cas.authn.mfa.gauth.name=mfa-gauth
cas.authn.mfa.gauth.failureMode=CLOSED
#cas.authn.mfa.gauth.cleaner.enabled=true
#cas.authn.mfa.gauth.cleaner.schedule.startDelay=20000
#cas.authn.mfa.gauth.cleaner.schedule.repeatInterval=60000
cas.authn.mfa.gauth.jpa.driverClass=org.hsqldb.jdbcDriver
cas.authn.mfa.gauth.jpa.url=jdbc:hsqldb:mem:cas-hsql-database
cas.authn.mfa.gauth.jpa.dialect=org.hibernate.dialect.HSQLDialect
cas.authn.mfa.gauth.jpa.user=sa
cas.authn.mfa.gauth.jpa.password=

dqv5.authn.mfa.email.name=mfa-email
dqv5.authn.mfa.email.code-length=6
dqv5.authn.mfa.email.expiration-seconds=300
dqv5.authn.mfa.email.accounts.casuser=casuser@example.com
