version: '3'
services:
  nginx:
    build: ./nginx/
    container_name: cas-demo-nginx
    ports:
      - "80:80"
    networks:
      - cas-demo-net
  cas:
    build: ./cas/
    container_name: cas-demo-cas
    ports:
      - "8080:8080"
    networks:
      - cas-demo-net
networks:
  cas-demo-net:
