server:
  port: 18001
spring:
  application:
    name: cas-client-1
cas:
  server-url-prefix: http://cas.example.org:8080/cas
  server-login-url: http://cas.example.org:8080/cas/login
  client-host-url: http://client1.demo.com:18001
  single-logout:
    enabled: true
