server:
  port: 18081
spring:
  application:
    name: cas-client-1
cas:
  server-url-prefix: https://cas.example.org:8443/cas
  server-login-url: https://cas.example.org:8443/cas/login
  client-host-url: https://client1.demo.com:18081
