server:
  port: 18002
spring:
  application:
    name: cas-client-2
cas:
  server-url-prefix: http://cas.example.org:8080/cas
  server-login-url: http://cas.example.org:8080/cas/login
  client-host-url: http://client2.demo.com:18002
