# Disable forced HTTPS for this demo.
cas.tgc.secure=false

# Disable the default static username/password authentication.
cas.authn.accept.users=

cas.authn.ldap[0].ldapUrl=ldap://localhost:389
cas.authn.ldap[0].useSsl=false

# LDAP Authentication/Search Settings
# https://duqian42707.github.io/cas/5.3.x/installation/Configuration-Properties-Common.html#ldap-authenticationsearch-settings

# DIRECT authenticates by binding directly with the formatted user DN.
cas.authn.ldap[0].type=DIRECT
cas.authn.ldap[0].dnFormat=uid=%s,ou=users,dc=company,dc=com
cas.authn.ldap[0].enhanceWithEntryResolver=false
cas.authn.ldap[0].validator.type=none
cas.authn.ldap[0].validateOnCheckout=false
cas.authn.ldap[0].validatePeriodically=false
cas.authn.ldap[0].poolPassivator=CLOSE

# AUTHENTICATED uses a service account to search the user DN first.
# cas.authn.ldap[0].type=AUTHENTICATED
# cas.authn.ldap[0].bindDn=cn=admin,dc=company,dc=com
# cas.authn.ldap[0].bindCredential=admin123
# cas.authn.ldap[0].baseDn=ou=users,dc=company,dc=com
# cas.authn.ldap[0].searchFilter=uid={user}
# cas.authn.ldap[0].subtreeSearch=true

cas.authn.ldap[0].principalAttributeId=uid
cas.authn.ldap[0].principalAttributeList=uid,cn,realName,userCode,deptName,deptCode
cas.authn.ldap[0].principalDnAttributeName=principalLdapDn
cas.authn.ldap[0].allowMultiplePrincipalAttributeValues=true
cas.authn.ldap[0].allowMissingPrincipalAttributeValue=true
cas.authn.ldap[0].credentialCriteria=
